# Request 
geometry_msgs/Vector3[] matrix_a
geometry_msgs/Vector3 vector_b
---
# Response
geometry_msgs/Vector3 x
# including displacement matrix and quaternion for rotation
geometry_msgs/Transform transformation